default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: beroot_dev
  user: sushi
  password: password

production:
  <<: *default
  database: beroot
  username: deploy
  password: new_password